title: 스마트 안전 및 제조 데이터 혁신
author: Hankyul Jeong
copyright: "2026 Hankyul Jeong. All rights reserved."
logo: ""
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - mermaid
    - colon_fence
repository:
  url: https://github.com/hangrydev/205-research-etri
  branch: main
launch_buttons:
  colab: true
html:
  use_repository_button: true
  use_issues_button: true
  home_page_in_navbar: false
  css:
    - _static/custom.css
    - _static/darkmode.css
sphinx:
  config:
    language: ko
    html_permalinks_icon: "<i class='fas fa-link'></i>"
    html_js_files:
      - force-light.js
